# Generated by Django 3.0.2 on 2020-04-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='items1',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='products',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabout.CustomerOrder'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
