# Generated by Django 3.0.2 on 2020-04-30 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabout', '0004_itemorder_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='userid1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabout.customer'),
        ),
    ]
