# Generated by Django 3.0.2 on 2020-04-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabout', '0005_customerorder_userid1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='userid1',
        ),
    ]
