# Generated by Django 3.0.2 on 2020-05-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabout', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='setsatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
