# Generated by Django 3.0.2 on 2020-05-16 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabout', '0010_remove_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='line_total',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fabout.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fabout.CustomerOrder'),
        ),
    ]
